var shuffleSequence = seq("intro", sepWith("sep",  seq("practice")), "practiceover", sepWith("sep", rshuffle(startsWith("first-item"), startsWith("firstfiller"))), seq("practice-two"), "practice-two-over", sepWith("sep", rshuffle(startsWith("followup"), startsWith("filler"))));

var continueMessage = ["Klikni zde"];

var aj = "AcceptabilityJudgment";

var q = "Question";

var completionMessage = "[Zadané odpovědi jsou odeslány na server. Děkujeme za spolupráci!]";

var ms = "Message";

var defaults = [    
    "Separator", { transfer: 800,
                   normalMessage: "Počkejte prosím na další položku v experimentu.",
                   errorMessage: "Špatně. Počkejte prosím na další položku v experimentu." 
		 },
    "AcceptabilityJudgment", { as: ["1", "2", "3", "4", "5"],
                               presentAsScale: true,
                               leftComment: "(absolutně nepřijatelná věta)", rightComment: "(věta je naprosto v pořádku)" },
    "Message", { hideProgressBar: true, transfer: "click" }
];

 var progressBarText = "";

var items = [ ["sep", "Separator", { }],
 
	      ["intro", "Form", {continueMessage: "Pro vstup do experimentu, klikněte zde", html: { include: "example_intro.html" }}],

	      ["practice", aj, {s: {html: "<p>Pavel uviděl Marušku.</p><p><i>Tato věta je v pořádku. Pokud souhlasíte, vyberte jednu z možností v pravém konci škály (nejspíš 5).</i></p>"}}],
["practice", aj, {s: {html: "Ačkoliv byla Marie unavená, navštívila včera ještě vedoucího hasičské jednotky Tříbětice.</p><p><i>Tato věta je v pořádku. Pokud souhlasíte, vyberte jako odpověď jednu z možností v pravém konci škály (nejspíš 5).</i></p>"}}],
["practice", aj, {s: {html: "Byla Marie unavená ačkoliv, navštívila včera ještě ho v Tříběticích.</p><p><i>Tato věta není v pořádku. Pokud souhlasíte, vyberte jako odpověď jednu z možností v levém konci škály (nejspíš 1).</i></p>"}}],

	      ["practiceover", "Message", {continueMessage: "Klikněte zde pro pokračování experimentu", html: ["div", ["p", "Zde končí přípravná část experimentu. Klikněte níže pro vstup do experimentu."]]}],

[["first-item1-acc-all", 1], aj, {s: "Všichni návštěvníci se sebemenším zájmem o archeologii zvládli tento exponát hned poznat."}],
[["first-item1-acc-most", 1], aj, {s: "Většina návštěvníků se sebemenším zájmem o archeologii zvládla tento exponát hned poznat."}],
[["first-item1-acc-some", 1], aj, {s: "Někteří návštěvníci se sebemenším zájmem o archeologii zvládli tento exponát hned poznat."}],

[["first-item2-acc-all", 2], aj, {s: "Všechny zákaznice se sebemenší alergií na odlakovač musely ze salonu preventivně odejít.s"}],
[["first-item2-acc-most", 2], aj, {s: "Většina zákaznic se sebemenší alergií na odlakovač musela ze salonu preventivně odejít."}],
[["first-item2-acc-some", 2], aj, {s: "Některé zákaznice se sebemenší alergií na odlakovač musely ze salonu preventivně odejít."}],


["firstfiller1", aj, {s: "Já, starý sadař nejsem přišel do lesa celé roky." }],
["firstfiller_item2", aj, {s: "Já, starý sadař, jsem nepřišel do lesa celé roky." }],
["firstfiller_item3", aj, {s: "Ten nový student bude zítra přečíst tu vyžádanou knihu." }],
["firstfiller_item4", aj, {s: "Ten nový student přečte zítra tu vyžádanou knihu." }],
["firstfiller_item5", aj, {s: "Černý kocour pronásledovala po dvorku bílou kočku." }],
["firstfiller_item6", aj, {s: "Bílá kočka pronásledovala po dvorku černého kocoura." }],
["firstfiller_item7", aj, {s: "Svůj dědeček viděl Karla na nádraží." }],
["firstfiller_item8", aj, {s: "Karel viděl svého dědečka na nádraží." }],
["firstfiller_item9", aj, {s: "Petr chtěl, aby mu Karel pomůže se štípáním dřeva." }],
["firstfiller_item10", aj, {s: "Petr přijel včera až do půlnoci." }],
["firstfiller_item11", aj, {s: "Petr přečetl tu novou knihu celou noc." }],
["firstfiller_item12", aj, {s: "Petr slyšel Karlem zpívat celou noc." }],
["firstfiller_item13", aj, {s: "Pět chlapci přišli na dvůr hrát fotbal." }],
["firstfiller_item14", aj, {s: "Trojice chlapců včera v baru vypila pivo každý." }],
["firstfiller_item15", aj, {s: "Každý student se sešel včera na dvorku." }],
["firstfiller_item16", aj, {s: "Petr přinesl na dvůr všechen pes." }],
["firstfiller_item17", aj, {s: "Většina chlapců přinesli zadaný úkol v pořádku." }],
["firstfiller_item18", aj, {s: "Málo dívek přišlo na schůzku pozdě." }],
["firstfiller_item19", aj, {s: "Petr včera přijít do obchodu a jíst ten salám." }],
["firstfiller_item20", aj, {s: "Koho Petr viděl muže, který na dvorku pozdravil?" }],
["firstfiller_item21", aj, {s: "Koho na dvorku Petr viděl Kláru a?" }],
["firstfiller_item22", aj, {s: "Koho Petr nevěděl, kdo včera pozdravil?" }],
["firstfiller_item23", aj, {s: "Mladý muž se mu, který kouřil cigaretu, představil." }],
["firstfiller_item24", aj, {s: "Mladý muž, který kouřil cigaretu, se mu představil." }],
["firstfiller_item25", aj, {s: "Petr přinesl do sběrného dvora dvě dveře." }],
["firstfiller_item26", aj, {s: "Petr viděl včera večer mladého muže a v parku." }],
["firstfiller_item27", aj, {s: "Petr vrátil do knihovny knihu a unavený." }],
["firstfiller_item28", aj, {s: "Ta loď se bohužel potopila křižníkem." }],
["firstfiller_item29", aj, {s: "Petr mával celý večer pes." }],
["firstfiller_item30", aj, {s: "Když jsem přišel, Karel už byl dvě hodiny odjet." }],


 ["practice-two", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/1_nd_wrong.jpg?raw=true\"></td><td><img style=\"display:block;max-width:400px;max-height:400px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/1_non-distributive.jpg?raw=true\"></td></table></center>Kontext: Aleš a Bedřich byli včera se svými manželkami na večírku. Obě manželky požádaly své manžele, aby je vyfotili. Aleš svoji manželku vyfotil, ale Bedřich ne, protože měl vybitý telefon.<center><p>Věta: <i>Pouze jeden manžel vyfotil svoji manželku.</i></p></p>Věta je adekvátní vůči kontextu a zároveň odpovídá levému obrázku, neboť na něm pouze jeden muž fotí ženu. Pravý obrázek neodpovídá, neboť na něm fotí dva muži. Odpověď <i>ani jeden</i> zde není adekvátní, protože k větě se hodí obrázek nalevo. Klikněte tedy na odpověď <i>levý</i>.</center>"}, hasCorrect: 0}],
             
["practice-two", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:400px;max-height:400px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/9_non-d_f.jpg?raw=true\"></td><td><img style=\"display:block;max-width:370px;max-height:370px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/9_nd.jpg?raw=true\"></td></table></center>Kontext: Děti si hrály na půdě, kde našly staré rozbité hračky. Byly z toho smutné. Přinesly je ukázat tatínkovi a prosily ho, zda by mohl rozbité hračky opravit.</p><center><p>Věta: <i>Každé dítě přineslo jednu hračku. </i></p></p>Věta je adekvátní vůči kontextu a zároveň odpovídá pravému obrázku, neboť na něm má každé dítě v ruce jednu hračku. Na levém obrázku nese hračku pouze holčička, zatímco chlapeček má prázdné ruce. Odpověď <i>ani jeden</i> zde není adekvátní, protože se k větě hodí obrázek napravo. Klikněte tedy na odpověď <i>pravý</i>.</center>"}, hasCorrect: 2}],
            
["practice-two", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:450px;max-height:450px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/3_d.jpg?raw=true\"></td><td><img style=\"display:block;max-width:610px;max-height:610px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/3_d_f.jpg?raw=true\"></td></table></center>Kontext: Alena přišla navštívit svoji sestru Mariku. Alena byla celý týden na dovolené, a proto jí uniklo několik dílů oblíbeného detektivního seriálu. Marika jí proto stručně vylíčila, co se tam odehrálo.</p><center><p>Věta: <i>Marika řekla, že policista Jan zatkl dva zloděje. </i></p></p>Věta je sice adekvátní vůči kontextu, ale ani jeden obrázek dané větě neodpovídá. Levý obrázek větě neodpovídá, protože jsou na něm dva policisté a každý z nich zatkl dva zloděje. Vyslovená věta ovšem zmiňuje pouze jednoho policistu. Pravý obrázek také neodpovídá, protože jsou na něm dva policisté a každý z nich zatkl jednoho zloděje. Ani jeden obrázek tedy neodpovídá větě. Zvolte možnost <i>ani jeden</i>.</center>"}, hasCorrect: 1}],             

          ["practice-two-over", "Message", {continueMessage: "Klikněte zde pro pokračování experimentu", html: ["div", ["p", "Zde končí přípravná část experimentu. Klikněte níže pro vstup do experimentu."]]}],

[["followup-item1-d-ref", 1], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/1_distributive.jpg?raw=true\"></td><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/1_d_wrong.jpg?raw=true\"></td></table></center> Kontext: Včera se konal v Praze večírek celebrit. Sešli se zde známí herci, zpěváci, modelky a samozřejmě novináři bulvárních časopisů. Večírku se zúčastnily také herečky Simona a Kamila. Šéfredaktoři přikázali novinářům pořídit fotografie ukazující temnou stránku celebrit. Novináři Karel a Jakub tedy doufali, že se jim pořadí pořídit kompromitující fotografie pozvaných osobností, které by mohly čtenáře časopisů zajímat.</p><center><p>Věta: <i> Karel i Jakub vyfotili dvě herečky.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],

[["followup-item1-d-svo", 1], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/1_distributive.jpg?raw=true\"></td><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/1_d_wrong.jpg?raw=true\"></td></table></center>Kontext: Včera se konal v Praze večírek celebrit. Sešli se zde známí herci, zpěváci, modelky a samozřejmě novináři bulvárních časopisů. Večírku se zúčastnily také herečky Simona a Kamila. Šéfredaktoři přikázali novinářům pořídit fotografie ukazující temnou stránku celebrit. Novináři Karel a Jakub tedy doufali, že se jim pořadí pořídit kompromitující fotografie pozvaných osobností, které by mohly čtenáře časopisů zajímat.</p><center><p>Věta: <i> Dva novináři vyfotili Simonu i Kamilu.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],

[["followup-item1-d-move-a", 1], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/1_distributive.jpg?raw=true\"></td><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/1_d_wrong.jpg?raw=true\"></td></table></center>Kontext: Včera se konal v Praze večírek celebrit. Sešli se zde známí herci, zpěváci, modelky a samozřejmě novináři bulvárních časopisů. Večírku se zúčastnily také herečky Simona a Kamila. Šéfredaktoři přikázali novinářům pořídit fotografie ukazující temnou stránku celebrit. Novináři Karel a Jakub tedy doufali, že se jim pořadí pořídit kompromitující fotografie pozvaných osobností, které by mohly čtenáře časopisů zajímat.</p><center><p>Věta: <i> Na večírku byly Simona i Kamila vyfoceny dvěma novináři.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],

[["followup-item1-d-move-abar", 1], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/1_distributive.jpg?raw=true\"></td><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/1_d_wrong.jpg?raw=true\"></td></table></center>Kontext: Včera se konal v Praze večírek celebrit. Sešli se zde známí herci, zpěváci, modelky a samozřejmě novináři bulvárních časopisů. Večírku se zúčastnily také herečky Simona a Kamila. Šéfredaktoři přikázali novinářům pořídit fotografie ukazující temnou stránku celebrit. Novináři Karel a Jakub tedy doufali, že se jim pořadí pořídit kompromitující fotografie pozvaných osobností, které by mohly čtenáře časopisů zajímat.</p><center><p>Věta: <i> Simonu i Kamilu dva novináři vyfotili až po půlnoci.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],
             

["filler1-bad", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:300px;max-height:300px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/1_nd_wrong.jpg?raw=true\"></td><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/1_d_wrong.jpg?raw=true\"></td></table></center>Kontext: Známý modní dům pořádal módní přehlídku nové kolekce. Bylo pozváno spoustu důležitých osob a také zástupci módních časopisů. Akci uzavírala noční přehlídka dvou světových modelek. Fotografové měli plné ruce práce.</p><center><p>Věta: <i>Každý fotograf vyfotil obě modelky.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],
           
["filler2-good-right", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:450px;max-height:450px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/3_d.jpg?raw=true\"></td><td><img style=\"display:block;max-width:600px;max-height:600px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/3_non-d_f.jpg?raw=true\"></td></table></center>Kontext: Policisté pronásledovali skupinu zlodějů aut. Ti byli po krátké honičce s policisty dopadeni v kradených autech. Některým policistům se podařilo dopadnout a zatknout více zlodějů, někteří zůstali s policejními psy a nezatkli žádného zločince.</p><center><p>Věta: <i>Pouze jeden policista zatkl jednoho zloděje.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}], 
             
["filler3-bad", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:300px;max-height:300px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/2_nd_wrong.jpg?raw=true\"></td><td><img style=\"display:block;max-width:300px;max-height:300px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/2_non-distributive.jpg?raw=true\"></td></table></center>Kontext: Na kutilském veletrhu si mohli účastníci vyzkoušet vyrobit předměty ze dřeva nebo železa pomocí starých středověkých postupů.</p><center><p>Věta: <i>Dva soutěžící vyrobili každý dva dřevěné výrobky.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],             
                         
["filler4-good-right", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:300px;max-height:300px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/5_distribtive.jpg?raw=true\"></td><td><img style=\"display:block;max-width:300px;max-height:300px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/5_d_wrong.jpg?raw=true\"></td></table></center>Kontext: Na policejním oddělení schválili dvě nové vyhlášky týkající se omezení rychlosti v některých částech města. Vyvěsit vyhlášku na úřední desku má v pravomoci úředník nebo policista.</p><center><p>Věta: <i>Pouze jedna osoba vyvěsila dvě vyhlášky na úřední desku.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],   
             
["filler5-bad", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:400px;max-height:400px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/4_d_wrong_new.jpg?raw=true\"></td><td><img style=\"display:block;max-width:320px;max-height:320px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/4_non-distributive_new.jpg?raw=true\"></td></table></center>Kontext: Starosta města uspořádal soutěž malířů. Prvním úkolem bylo natřít dva domy v určitém časovém limitu. Ti, kteří to zvládli, pokračovali do dalšího kola.</p><center><p>Věta: <i>Každý malíř zvládl natřít oba domy v daném limitu.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],    
             
["filler6-good-left", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/8_d_wrong_new.jpg?raw=true\"></td><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/8_distributive_new.jpg?raw=true\"></td></table></center>Kontext: Večerní televizní zprávy informovaly občany o dvou zlodějích, kteří vykrádají obchody. Většinou se snaží získat pouze peníze nebo věci, které by mohli později prodat. Někdy se bohužel uchylují i k násilí.</p><center><p>Věta: <i>Pouze jeden zloděj bodl prodavače.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],  
             
["filler7-bad", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:300px;max-height:300px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/6_nd_wrong.jpg?raw=true\"></td><td><img style=\"display:block;max-width:300px;max-height:300px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/6_d_wrong.jpg?raw=true\"></td></table></center>Kontext: Nový díl televizního seriálu <i>Naše město</i> se odehrával především v nemocnici, kde lékař Marek s lékařkou Annou ošetřovali zraněného dědečka s vnukem po autonehodě. Samozřejmě nechyběla romantická scéna mezi Markem a Annou.</p><center><p>Věta: <i>Dva lékaři ošetřili každý dva pacienty.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}], 
             
["filler8-good-left", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:380px;max-height:380px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/9_d_f.jpg?raw=true\"></td><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/9_nd.jpg?raw=true\"></td></table></center>Kontext: Dědeček měl radost, že se děti na oslavě jeho narozenin chovají vzorně a v klidu si hrají. Pak ale přišla jeho nejstarší dcera se svými dětmi, kteří jsou pěkní rošťáci a rády ničí hračky. Díky přísnému tatínkovi se téměř nic nestalo.</p><center><p>Věta: <i>Pouze jedno dítě zničilo jednu hračku.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],  
             
["filler9-bad", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:390px;max-height:390px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/7_nd_wrong%20new.jpg?raw=true\"></td><td><img style=\"display:block;max-width:390px;max-height:390px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/7_non-distributive.jpg?raw=true\"></td></table></center>Kontext: Velmi oblíbenou počítačovou hrou se stali <i>Zabijáčtí roboti</i>. Tuto hru je možné hrát i s kamarády. Hráč si vybere jednoho robota. Úkolem je zabít určitý počet vojáků, a poté se hráč dostane na vyšší level hry.</p><center><p>Věta: <i>V prvním levelu hry každý robot zabil dva vojáky.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],             
             
["filler10-good-left", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:330px;max-height:330px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/10_non-distributive.jpeg?raw=true\"></td><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/10_nd_wrong.jpeg?raw=true\"></td></table></center>Kontext: Na dětském dnu měly děti za úkol vyrobit vlajku a s pomocí rodičů ji pověsit. Za odměnu pak získaly sladkosti.</p><center><p>Věta: <i>Každé dítě vyrobilo jednu vlajku.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],  
             
["filler11-bad", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:450px;max-height:450px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/11_distributive.jpeg?raw=true\"></td><td><img style=\"display:block;max-width:450px;max-height:450px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/11_d_wrong.jpeg?raw=true\"></td></table></center>Kontext: Kniha <i>Jupiter</i> je po několik desetiletí oblíbenou dětskou knihou. Vyšla v několika edicích, ovšem pouze u jednoho nakladatelství.</p><center><p>Věta: <i>Pouze nakladatelství <i>Host<i> vydalo knihu <i>Jupiter</i>.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],    
             
["filler12-good-left", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:430px;max-height:430px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/12_non-distributive.jpeg?raw=true\"></td><td><img style=\"display:block;max-width:450px;max-height:450px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/12_nd_wrong.jpeg?raw=true\"></td></table></center>Kontext: Ve středověku se lidé scházeli na trzích, kde kupovali nebo prodávali různé předměty. Někteří prodávající předměty vyráběli přímo na místě.</p><center><p>Věta: <i>Dva vesničané vyrobili dva předměty ze železa. </i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],              
             
["filler13-bad", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/13_d_wrong.jpg?raw=true\"></td><td><img style=\"display:block;max-width:370px;max-height:370px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/13_nd_wrong.jpeg?raw=true\"></td></table></center>Kontext: Děti si při hře v lese roztrhly oblečení. Maminky z toho nebyly šťastné, ale rozhodly se, že dětem oblečení zašijí.</p><center><p>Věta: <i>Dvě maminky zašily dvě trička.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],     
             
["filler14-good-right", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:400px;max-height:400px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/14_nd.jpg?raw=true\"></td><td><img style=\"display:block;max-width:430px;max-height:430px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/14_d_f.jpeg?raw=true\"></td></table></center>Kontext: Farmář má velmi rád svá zvířata a dobře se o ně stará. Někdy ovšem, když má špatný den, nakopne slepice, které se mu pořád pletou pod nohy.</p><center><p>Věta: <i>Dnes farmář nakopl jednu slepici.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],        
                               
["filler15-bad", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:300px;max-height:300px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/15_distributive.JPG?raw=true\"></td><td><img style=\"display:block;max-width:300px;max-height:300px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/15_non-distributive.jpg?raw=true\"></td></table></center>Kontext: Děti dostaly nové míčky různých barev. Odpoledne si s nimi házely o zeď. Tatínek se obával, že děti rozbijí míčkem okno, což se také stalo.</p><center><p>Věta: <i>Pouze červený míček rozbil okno.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],      
             
["filler16-good-right", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:400px;max-height:400px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/16_non-distributive.jpeg?raw=true\"></td><td><img style=\"display:block;max-width:400px;max-height:400px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/16_distributive.jpeg?raw=true\"></td></table></center>Kontext: Část lesa byla napaden kůrovcem, a proto se lesníci rozhodli, že stromy pokácí a vysadí nové.</p><center><p>Věta: <i>Dva lesníci pokáceli každý dva stromy.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],
             
                     

];
